Respuestas/php/laravel/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ContactosController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



 
//Route::resource('/', ContactosController::class);
Route::resource('contactos', ContactosController::class);


Route::get('/', function () {
    return view('welcome');
});

Respuestas/php/laravel/app/Models/Contactos.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Contactos extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'email', 'phone', 'age', 'active'];

}

Respuestas/php/laravel/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

Respuestas/php/laravel/app/Http/Controllers/ContactosController.php
<?php

namespace App\Http\Controllers;
use App\Models\Contactos;
use Illuminate\Http\Request;

class ContactosController extends Controller
{
    //
    public function index()
    {
        $contactos = Contactos::all();
        return view('index', compact('contactos'));
    }


    public function create()
    {
        return view('create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'email' => 'required',
            'phone' => 'required',
            'age' => 'required',
        ]);
        
        Contactos::create($request->post());

        return redirect()->route('contactos.index')->with('success','Se ha creado satifactoriamente el contacto '. $request->name);
    }

    public function edit(Contactos $contacto)
    {
        return view('edit',compact('contacto'));
    }


    public function update(Request $request, Contactos $contacto)
    {
        
        $request->validate([
            'name' => 'required',
            'email' => 'required',
            'phone' => 'required',
            'age' => 'required',
        ]);
        
        $contacto->fill($request->post())->save();

        return redirect()->route('contactos.index')->with('success','el contacto '. $contacto->name .' ha sido actualizado');
    }

    public function destroy(Contactos $contacto)
    {
        $contacto->delete();
        return redirect()->route('contactos.index')->with('success','El contacto '. $contacto->name .' ha sido eliminado');
    }
}

Respuestas/php/laravel/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

Respuestas/php/laravel/resources/views/create.blade.php
<!doctype html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>

    <div class="w-3/5 mx-auto my-6">

        <div class="my-6">
            <a href="https://itnazca.com/" target='_blank'>
                <img src="https://itnazca.com/images/logo.png" alt="" class="my-6">
            </a>
            <h1 class="text-3xl font-bold my-3 text-lime-700">Prueba de Desarrollo: Laravel</h1>
            <h2 class="text-xl">01 - CRUD</h2>
        </div>

        <div class="bg-lime-200 p-7 mt-2">
        
            <div class="bg-black text-white p-3">
                <p class="my-2 font-bold text-lg text-yellow-300">Crear Contactos</p>
            </div>

            <div class="mt-10">
            
            <a href="{{ route('contactos.index') }}" class='bg-lime-900 hover:bg-lime-500 hover:text-lime-900 text-white px-4 py-3 rounded-lg'>Ver lista de contactos</a>

            
            <div class="relative overflow-x-auto mt-10">
                
            <form action="{{ route('contactos.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                
                <div class="grid grid-cols-4 gap-4">

                <div class='group-fields my-2 col-span-4'>
                    <label for="Nombre" class='py-3'>Nombre</label>
                    <div>
                        <input type="text" class='px-4 py-2 mt-3 rounded-lg w-full' placeholder='Ingresar Nomnbre' name='name'>

                        @error('name')
                        <div class="bg-red-500 px-3 py-2 text-white text-sm mt-2 rounded-lg">{{ $message }}</div>
                        @enderror
                    </div>
                </div>

                <div class='group-fields my-2 col-span-4'>
                    <label for="Nombre" class='py-3'>Correo</label>
                    <div>
                        <input type="text" class='px-4 py-2 mt-3 rounded-lg w-full' placeholder='Ingresar Correo' name='email'>
                        @error('email')
                        <div class="bg-red-500 px-3 py-2 text-white text-sm mt-2 rounded-lg">{{ $message }}</div>
                        @enderror
                    </div>
                </div>

                <div class='group-fields my-2 col-span-2'>
                    <label for="Nombre" class='py-3'>Teléfono</label>
                    <div>
                        <input type="text" class='px-4 py-2 mt-3 rounded-lg w-full' placeholder='Ingresar Teléfono' name='phone'>
                        @error('phone')
                        <div class="bg-red-500 px-3 py-2 text-white text-sm mt-2 rounded-lg">{{ $message }}</div>
                        @enderror
                    </div>
                </div>

                <div class='group-fields my-2 col-span-2'>
                    <label for="Nombre" class='py-3'>Edad</label>
                    <div>
                        <input type="text" class='px-4 py-2 mt-3 rounded-lg w-full' placeholder='Ingrese Edad' name='age'>
                        @error('age')
                        <div class="bg-red-500 px-3 py-2 text-white text-sm mt-2 rounded-lg">{{ $message }}</div>
                        @enderror
                    </div>
                </div>

                <div>
                    <button type="submit" class="bg-lime-900 hover:bg-lime-500 hover:text-lime-900 text-white px-4 py-3 rounded-lg justify-items-center">Submit</button>    
                </div>
                

                </div>

            </form>
            

            </div>

                
            </div>

        </div>

        <div class="mt-8">
            <p class="text-slate-400">@julioIzquierdoMejia</p>
        </div>

    </div>

    
  
</body>
</html>

Respuestas/php/laravel/resources/views/edit.blade.php
<!doctype html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>

    <div class="w-3/5 mx-auto my-6">

        <div class="my-6">
            <a href="https://itnazca.com/" target='_blank'>
                <img src="https://itnazca.com/images/logo.png" alt="" class="my-6">
            </a>
            <h1 class="text-3xl font-bold my-3 text-lime-700">Prueba de Desarrollo: Laravel</h1>
            <h2 class="text-xl">01 - CRUD</h2>
        </div>

        <div class="bg-lime-200 p-7 mt-2">
        
            <div class="bg-black text-white p-3">
                <p class="my-2 font-bold text-lg text-yellow-300">Crear Contactos</p>
            </div>

            <div class="mt-10">
            
            <a href="{{ route('contactos.index') }}" class='bg-lime-900 hover:bg-lime-500 hover:text-lime-900 text-white px-4 py-3 rounded-lg'>Ver lista de contactos</a>

            
            <div class="relative overflow-x-auto mt-10">
            
            <form action="{{ route('contactos.update',$contacto->id) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="grid grid-cols-4 gap-4">

                <div class='group-fields my-2 col-span-4'>
                    <label for="Nombre" class='py-3'>Nombre</label>
                    <div>
                        <input type="text" class='px-4 py-2 mt-3 rounded-lg w-full' placeholder='Ingresar Nomnbre' name='name' value="{{ $contacto->name }}">

                        @error('name')
                        <div class="bg-red-500 px-3 py-2 text-white text-sm mt-2 rounded-lg">{{ $message }}</div>
                        @enderror
                    </div>
                </div>

                <div class='group-fields my-2 col-span-4'>
                    <label for="Nombre" class='py-3'>Correo</label>
                    <div>
                        <input type="text" class='px-4 py-2 mt-3 rounded-lg w-full' placeholder='Ingresar Correo' name='email' value="{{ $contacto->email }}">
                        @error('email')
                        <div class="bg-red-500 px-3 py-2 text-white text-sm mt-2 rounded-lg">{{ $message }}</div>
                        @enderror
                    </div>
                </div>

                <div class='group-fields my-2 col-span-2'>
                    <label for="Nombre" class='py-3'>Teléfono</label>
                    <div>
                        <input type="text" class='px-4 py-2 mt-3 rounded-lg w-full' placeholder='Ingresar Teléfono' name='phone' value="{{ $contacto->phone }}">
                        @error('phone')
                        <div class="bg-red-500 px-3 py-2 text-white text-sm mt-2 rounded-lg">{{ $message }}</div>
                        @enderror
                    </div>
                </div>

                <div class='group-fields my-2 col-span-2'>
                    <label for="Nombre" class='py-3'>Edad</label>
                    <div>
                        <input type="text" class='px-4 py-2 mt-3 rounded-lg w-full' placeholder='Ingrese Edad' name='age' value="{{ $contacto->age }}">
                        @error('age')
                        <div class="bg-red-500 px-3 py-2 text-white text-sm mt-2 rounded-lg">{{ $message }}</div>
                        @enderror
                    </div>
                </div>

                <div>
                    <button type="submit" class="bg-lime-900 hover:bg-lime-500 hover:text-lime-900 text-white px-4 py-3 rounded-lg justify-items-center">Edit</button>    
                </div>
                

                </div>

            </form>
            

            </div>

                
            </div>

        </div>

        <div class="mt-8">
            <p class="text-slate-400">@julioIzquierdoMejia</p>
        </div>

    </div>

    
  
</body>
</html>

Respuestas/php/laravel/resources/views/index.blade.php
<!doctype html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.tailwindcss.com"></script>
<link rel="stylesheet" href="sweetalert2.min.css">
</head>
<body>

    <div class="w-3/5 mx-auto my-6">

        <div class="my-6">
            <a href="https://itnazca.com/" target='_blank'>
                <img src="https://itnazca.com/images/logo.png" alt="" class="my-6">
            </a>
            <h1 class="text-3xl font-bold my-3 text-lime-700">Prueba de Desarrollo: Laravel</h1>
            <h2 class="text-xl">01 - CRUD</h2>
        </div>

        <div class="bg-lime-200 p-7 mt-2">
        
            <div class="bg-black text-white p-3">
                <p class="my-2 font-bold text-lg text-yellow-300">Contactos</p>

                @if ($message = Session::get('success'))
                    <div class="alert alert-success">
                        <p>{{ $message }}</p>
                    </div>
                @endif
                
            </div>

            <div class="mt-10">
            
            <a href="{{ route('contactos.create') }}" class='bg-lime-900 hover:bg-lime-500 hover:text-lime-900 text-white px-4 py-3 rounded-lg'>Agregar Contacto</a>

            
            <div class="relative overflow-x-auto mt-10">
                <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
                    <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                        <tr>
                            <th scope="col" class="px-6 py-3">
                                Nombre
                            </th>
                            <th scope="col" class="px-6 py-3">
                                Correo
                            </th>
                            <th scope="col" class="px-6 py-3">
                                Telefono
                            </th>
                            <th scope="col" class="px-6 py-3">
                                Edad
                            </th>
                            <th scope="col" class="px-6 py-3">
                                Estado
                            </th>
                            <th scope="col" class="px-6 py-3">
                                Acciones
                            </th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach($contactos as $contacto)
                        
                        <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                            <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                                {{ $contacto->name }}
                            </th>
                            <td class="px-6 py-4">
                                {{ $contacto->email }}
                            </td>
                            <td class="px-6 py-4">
                                {{ $contacto->phone }}
                            </td>
                            <td class="px-6 py-4">
                                {{ $contacto->age }}
                            </td>
                            <td class="px-6 py-4">
                                @if($contacto->active == 1)
                                    <span>Activo</span>
                                @else
                                    <span>Inactivo</span>
                                @endIf
                            </td>
                            <td class="px-6 py-4">
                                <form action="{{ route('contactos.destroy',$contacto->id) }}" method="Post">
                                    <a class="bg-blue-500 text-white px-3 py-2 text-dm" href="{{ route('contactos.edit',$contacto->id) }}">Edit</a>
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="bg-red-500 text-white px-3 py-2 text-dm">Delete</button>
                                </form>
                            </td>
                        </tr>
                        @endForEach
                    </tbody>
                </table>
            </div>

                
            </div>

        </div>

        <div class="mt-8">
            <p class="text-slate-400">@julioIzquierdoMejia</p>
        </div>

    </div>
    
</body>
</html>